export enum CompanyActionType {
    VIEW_PROFILE = 'VIEW_PROFILE',
    CONTACT_TALENT = 'CONTACT_TALENT',
    ADVANCED_FILTERS = 'ADVANCED_FILTERS',
    CREATE_CHALLENGE = 'CREATE_CHALLENGE',
    ACCESS_METRICS = 'ACCESS_METRICS',
    ACCESS_REPORTS = 'ACCESS_REPORTS'
}